---
variant: fcos
version: 1.1.0
storage:
  directories:
    - path: /etc/opt/diaspora
      mode: 0755
  files:
    - path: /etc/opt/diaspora/database.yml
      mode: 0644
      overwrite: true
      contents:
        inline: |
          postgresql: &postgresql
            adapter: postgresql
            host: ${postgresql_ip}
            port: 5432
            username: diaspora
            password: ${postgres_password}
            encoding: unicode

          mysql: &mysql
            adapter: mysql2
            host: "localhost"
            port: 3306
            username: "root"
            password: ""
          #  socket: /tmp/mysql.sock
            encoding: utf8mb4
            collation: utf8mb4_bin


          # Comment the postgresql line and uncomment the mysql line
          # if you want to use mysql
          common: &common
            # Choose one of the following
            <<: *postgresql
            #<<: *mysql

            # Should match environment.sidekiq.concurrency
            #pool: 25

          ##################################################
          #### CONFIGURE ABOVE #############################
          ##################################################

          # Normally you don't need to touch anything here

          combined: &combined
            <<: *common
          development:
            <<: *combined
            database: diaspora_development
          production:
            <<: *combined
            database: diaspora_production
          test:
            <<: *combined
            database: "diaspora_test"
          integration1:
            <<: *combined
            database: diaspora_integration1
          integration2:
            <<: *combined
            database: diaspora_integration2
    - path: /etc/opt/diaspora/diaspora.yml
      mode: 0644
      overwrite: true
      contents:
        inline: |
          configuration:
            environment:
              url: "https://${diaspora_server_name}"
              require_ssl: true
              certificate_authorities: '/etc/ssl/certs/ca-certificates.crt'
              redis: 'redis://${redis_ip}'
              sidekiq:
                concurrency: 25
            server:
              listen: 'tcp://0.0.0.0:3000'
              rails_environment: 'production'
            privacy:
              statistics:
                user_counts: ${display_statistics}
                post_counts: ${display_statistics}
                comment_counts: ${display_statistics}
            settings:
              enable_registrations: ${enable_registrations}
              autofollow_on_join: ${autofollow_podmin}
              autofollow_on_join_user: '${admin_account}@${diaspora_server_name}'
              welcome_message:
                enabled: ${enable_welcome_message}
                subject: Welcome Message
                text: Hello %%{username}, welcome to diaspora.
              terms:
                enable: ${terms_enable}
                jurisdiction: ${terms_jurisdication}
              maintenance:
                remove_old_users:
                  enable: ${remove_old_users}
                  after_days: 365
                  warn_days: 30
            mail:
              enable: true
              sender_address: 'diaspora@${diaspora_server_name}'
              method: 'smtp'
              smtp:
                host: '${smtpd_ip}'
                port: 25
                authentication: 'none'
                domain: '${diaspora_server_name}'
            admins:
              account: ${admin_account}
              podmin_email: '${admin_email}'
          production:
            environment:
              #redis: 'redis://production.example.org:6379'
    - path: /etc/opt/diaspora/diaspora.toml
      mode: 0644
      overwrite: yes
      contents: |
          [configuration.environment]
          url = "https://${diaspora_server_name}"
          certificate_authorities = "/etc/ssl/certs/ca-certificates.crt"
          redis = "redis://${redis_ip}"
          require_ssl = true

          [configuration.environment.sidekiq]
          concurrency = 25

          [configuration.environment.logging]
          debug.sql = false
          debug.federation = false

          [configuration.server]
          listen = "tcp://0.0.0.0:3000"
          rails_environment = "production"
          unicorn_worker = 4

          [configuration.privacy.statistics]
          user_counts = ${display_statistics}
          post_counts = ${display_statistics}
          comment_counts = ${display_statistics}

          [configuration.settings]
          enable_registrations = ${enable_registrations}
          autofollow_on_join = ${autofollow_podmin}
          autofollow_on_join_use = "${admin_account}@${diaspora_server_name}"
          #liberapay_username =
          export_concurrency = 2

          [configuration.settings.welcome_message]
          enabled: ${enable_welcome_message}
          subject: "Welcome Message"
          text: "Hello %%{username}, welcome to diaspora."

          [configuration.settings.captcha]
          captcha_length = 10
          image_style = "simply_green"
          distortion = "high"

          [configuration.settings.terms]
          enable = ${terms_enable}
          jurisdiction = "${terms_jurisdication}"

          [configuration.settings.maintenance]
          remove_old_users.enable = ${remove_old_users}
          remove_old_users.after_days = 365
          remove_old_users.warn_days = 30

          [configuration.mail]
          enable = true
          sender_address = "diaspora@${diaspora_server_name}"
          method = "smtp"

          [configuration.mail.smtp]
          host = "${smtpd_ip}"
          port = 25
          authentication: "none"
          domain = "${diaspora_server_name}"

          [configuration.admins]
          account = "${admin_account}"
          podmin_email = "${admin_email}"

          [production]
...
